#!/bin/sh

# echo 'Unconfigured tinc-up script, please edit '$0'!'

#ifconfig $INTERFACE <your vpn IP address> netmask <netmask of whole VPN>

ip link set $INTERFACE up
ip addr add 192.168.0.1/24 dev $INTERFACE

iptables -P FORWARD ACCEPT
